Adding Askubuntu and playstore
ArjunSharda/Searchor pull request #110
Opened 2022-10-07 18:45 UTC by viciousButterfly

## What is this Pull Request About?

## What will this Pull Request Affect?

# Any additional information?

2022-10-07 18:57 UTC, ArjunSharda requested changes
Looks good to me, but can you please push the code to change the name to what i've suggested? Searchor's codebase follows the UpperCamelCase convention.

2022-10-07 18:57 UTC, ArjunSharda commented on src/searchor/__init__.py
> +    Playstore = "https://play.google.com/store/search?q={query}"
```suggestion
    GooglePlayStore = "https://play.google.com/store/search?q={query}"
```

2022-10-07 18:57 UTC, ArjunSharda commented on src/searchor/__init__.py
> +    Askubuntu = "https://askubuntu.com/search?q={query}"
```suggestion
    AskUbuntu = "https://askubuntu.com/search?q={query}"
```

2022-10-07 19:52 UTC, viciousButterfly commented on src/searchor/__init__.py
> +    Askubuntu = "https://askubuntu.com/search?q={query}"
Yes I'll

2022-10-07 20:02 UTC, viciousButterfly commented
Added AskUbuntu and GooglePlayStore with the mentioned changes in the naming convention

2022-10-08 13:35 UTC, ArjunSharda commented on src/searchor/__init__.py
> +    PyP = "https://pypi.org/search/?q={query}"
```suggestion
    PyPi = "https://pypi.org/search/?q={query}"

2022-10-08 20:42 UTC, ArjunSharda approved these changes
LGTM! Will merge in the next latest update.

2022-10-09 05:53 UTC, itskegnh approved these changes

2022-10-11 16:11 UTC, merged