Introduce docker
ArjunSharda/Searchor pull request #134
Opened 2022-10-29 11:06 UTC by TanmayPatil105

## What is this Pull Request About?
Dockerfile created to build and test `searchor`.

## What will this Pull Request Affect?

FIles `Dockerfile`, `.dockerignore` and `requirements.txt` have been added.

# Any additional information?

README.md can be modified and the following line can be added.
```Docker
sudo docker built -t searchor .
```

2022-10-29 18:58 UTC, ArjunSharda requested changes
Hi! I think the custom uses aenum, so i've requested a change for that.

2022-10-29 18:58 UTC, ArjunSharda commented on requirements.txt
> +pyperclip
```suggestion
pyperclip, aenum
```

2022-10-30 01:02 UTC, TanmayPatil105 commented
I think we do not need requirements.txt. They are getting installed during installation of searchor since they are mentioned in `setup.py`.

## Screenshot 
![image](https://user-images.githubusercontent.com/92677342/198858040-c869aa21-4fe2-4cce-88b9-8a4bf52383bb.png)

2022-10-30 22:36 UTC, ArjunSharda approved these changes
Thanks for the PR, LGTM! Happy Hacktoberfest!

2022-10-31 09:04 UTC, itskegnh approved these changes

2022-10-31 12:22 UTC, merged

2022-10-31 13:16 UTC, TanmayPatil105 commented
Thanks for merging :)