Add about docker to README.md
ArjunSharda/Searchor pull request #135
Opened 2022-11-02 11:38 UTC by youpong

## What is this Pull Request About?

Add following procedures about docker to README.md

- Building the docker image
- Running searcher on the docker container

## What will this Pull Request Affect?

Update README.md

# Any additional information?

There was a plan to update README.md in #134, but it seems to be missing.

2022-11-02 12:26 UTC, ArjunSharda requested changes
Hi! Thanks for the PR. There seems to be some typos, so I have requested the changes for them.

2022-11-02 12:26 UTC, ArjunSharda commented on README.md
> +$ docker build -t searcher .
```suggestion
$ docker build -t searchor .
```

2022-11-02 12:26 UTC, ArjunSharda commented on README.md
> +$ docker run --rm -it searcher bash
```suggestion
$ docker run --rm -it searchor bash
```

2022-11-02 12:26 UTC, ArjunSharda commented on README.md
> +Running searcher on the docker container
```suggestion
Running searchor on the docker container
```

2022-11-02 13:11 UTC, youpong commented
Sorry for that. I fixed them.

2022-11-04 01:46 UTC, ArjunSharda requested changes
I think you have to remove the root part. Sorry for late reply, thought it sent.

2022-11-04 17:15 UTC, youpong commented
I think that root part will be useful for who want to develop and test Searchor in a docker container.

2022-11-04 17:19 UTC, ArjunSharda commented
> I think that root part will be useful for who want to develop and test Searchor in a docker container.

Ah, then okay you can keep it.

2022-11-04 17:36 UTC, ArjunSharda approved these changes
LGTM, thanks for the PR!

2022-11-04 17:36 UTC, merged