#95 Added Docker Hub search Query Engine
ArjunSharda/Searchor pull request #96
Opened 2022-10-04 23:00 UTC by ritishbhardwaj

## What is this Pull Request About?

To add search engine query for Docker Hub 
useful in DevOps

## What will this Pull Request Affect?
will show the respective or required registry for containerization

# Any additional information?

2022-10-04 23:01 UTC, ritishbhardwaj commented
@ArjunSharda 
kindly merge this PR

2022-10-05 00:03 UTC, ArjunSharda requested changes
I've left a suggestion. Can you please commit it and then in the next update I can merge it?

2022-10-05 00:03 UTC, ArjunSharda commented on src/searchor/__init__.py
> +    DockerHub= "https://hub.docker.com/search?q={query}"
```suggestion
    DockerHub = "https://hub.docker.com/search?q={query}"
```

2022-10-05 03:24 UTC, ritishbhardwaj commented
@ArjunSharda  
sure, and please checkout i have made the change

2022-10-05 12:29 UTC, ArjunSharda approved these changes
LGTM! Will merge in the next update.

2022-10-06 12:56 UTC, merged